name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t mrinal2100/docker-react1 -f Dockerfile.dev .

      - name: Run Tests inside Docker
        run: docker run -e CI=true mrinal2100/docker-react1 npm run test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x "*.git*"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21 # Updated version
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-gh
          environment_name: Dockergh-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-610924852117
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip